language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
script:
- npm run test:unit
after_script:
- cat ./coverage/lcov.info | coveralls
deploy:
  provider: heroku
  api_key:
    secure: OnUN9Pq7V6F1OJqZ6hybqW5wnCPujYluhYRGkTeu7uXBdEnKIe2aiTY6GX33D0BLU/iAVos8Jg95yLS9VtIBg4RqkauQs9bpLlbddlrNT8gHTg9FlXKXlIOOXmLTLTjeDidtgG1+JWoaeJXPOid9TEXSx8piWHw2EGfmjLvAgSYwt2yNQWCqkCGxMGTA+Ygb8A8DW376fw3SrQJFGNFoKBDdhy6VHgF2bLwEAu6WOl+kmt1z3+Ogg9NFWEjA05v8b/GTMM1cmXESdTC5OkF19rfUj7/nDra16X1kumGeLV6ikdShLZUutjJIa8ztt/jHauVeIvuh23ShVHtUARREh+Lf+BmQZnhZg/xX55W7Tb0qMU33P64I3X1ublWojqqndYvUPQ1+bV3hvwWV/mtnZ99f6NjdmGCO3RzEQyuYY1EyvG2XJc0yKzKnCUfPvFWpVq2rn3fR5mz/Srq7u2ubO5rKcCP7xh6SpAOgwlUAAjTLHf2pUHBYhOplyuCJnptFyU1wK1y8sXCq6c366QMdh8HqwZFRDB1X1Rgu3aDmTzIfd42YnidR0JNNMAYiqrA/5r3lQHTnhWLOTujIa/KAXtIVbjzHPwNQxMMRhPIqWpMzqpF633CQvlXBqCETNqLGycXDIawR+1rKMVhISgSbjogYlNAEmoK0FCdqK1lZPCw=
